/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmRouteImport } from './routes/algorithm'
import { Route as DataRouteImport } from './routes/data'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as LinkageRouteImport } from './routes/linkage'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as SeriesRouteImport } from './routes/series'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmRoute = AlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkageRoute = LinkageRouteImport.update({
  id: '/linkage',
  path: '/linkage',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithm': typeof AlgorithmRoute
  '/data': typeof DataRoute
  '/forecast': typeof ForecastRoute
  '/linkage': typeof LinkageRoute
  '/literature': typeof LiteratureRoute
  '/paper': typeof PaperRoute
  '/series': typeof SeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithm': typeof AlgorithmRoute
  '/data': typeof DataRoute
  '/forecast': typeof ForecastRoute
  '/linkage': typeof LinkageRoute
  '/literature': typeof LiteratureRoute
  '/paper': typeof PaperRoute
  '/series': typeof SeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithm': typeof AlgorithmRoute
  '/data': typeof DataRoute
  '/forecast': typeof ForecastRoute
  '/linkage': typeof LinkageRoute
  '/literature': typeof LiteratureRoute
  '/paper': typeof PaperRoute
  '/series': typeof SeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithm'
    | '/data'
    | '/forecast'
    | '/linkage'
    | '/literature'
    | '/paper'
    | '/series'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithm'
    | '/data'
    | '/forecast'
    | '/linkage'
    | '/literature'
    | '/paper'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/algorithm'
    | '/data'
    | '/forecast'
    | '/linkage'
    | '/literature'
    | '/paper'
    | '/series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmRoute: typeof AlgorithmRoute
  DataRoute: typeof DataRoute
  ForecastRoute: typeof ForecastRoute
  LinkageRoute: typeof LinkageRoute
  LiteratureRoute: typeof LiteratureRoute
  PaperRoute: typeof PaperRoute
  SeriesRoute: typeof SeriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithm': {
      id: '/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof AlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkage': {
      id: '/linkage'
      path: '/linkage'
      fullPath: '/linkage'
      preLoaderRoute: typeof LinkageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmRoute: AlgorithmRoute,
  DataRoute: DataRoute,
  ForecastRoute: ForecastRoute,
  LinkageRoute: LinkageRoute,
  LiteratureRoute: LiteratureRoute,
  PaperRoute: PaperRoute,
  SeriesRoute: SeriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
